Output modules/fuzzy/demos/ff.gif

Set TypingSpeed 75ms
Set Shell zsh
Set FontSize 22
Set Width 1300
Set Height 750

Env HOME "/Users/dsalazar"
Env BAT_THEME "Catppuccin Mocha"
Env FZF_DEFAULT_OPTS "--height 80% --border --layout=reverse --info=inline --ansi --ignore-case --preview-window right:50%"

Hide
Type "cd /Users/dsalazar/env"
Enter
Ctrl+L
Show

Sleep 500ms
Type "ff default.nix"
Sleep 1s
Enter
Sleep 1500ms
Down
Sleep 500ms
Down
Sleep 500ms
Enter
Sleep 2s
